warehouse_system/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from inventory import views

inventory_patterns =[
    path('', views.InventoryView.as_view()),
    re_path(r'(?P<id>\d+)', views.ShowInventory.as_view()),
    path('products/', views.ProductsAvaliableView.as_view()),
    path('storages/', views.StorageContainsView.as_view()),
]

urlpatterns = [
    path('', views.index, name='home'),
    path('inventory/', include(inventory_patterns)),
    path('admin/', admin.site.urls),

    
]

inventory/models.py
from django.db import models

# ________________________________Products_____________________________________
class Country(models.Model):

    name:models.CharField = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Supplier(models.Model):

    name:models.CharField = models.CharField(max_length=50)
    contact_info:models.CharField = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class ProductModel(models.Model):

    name:models.CharField = models.CharField(max_length=50)
    description:models.CharField = models.CharField(max_length=200)

    def __str__(self) -> str:
        if self.name is not None:
            return self.name
        else:
            return 'empty pm'


class ProductPrototype(models.Model):

    name:models.CharField = models.CharField(max_length=50)
    description:models.CharField = models.CharField(max_length=200)
    supplier:models.ForeignKey = models.ForeignKey(Supplier, on_delete=models.PROTECT)
    country:models.ForeignKey = models.ForeignKey(Country, on_delete=models.PROTECT)
    model:models.ForeignKey = models.ForeignKey(ProductModel, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:

        if self.name is None:
            return "Unnamed ProductPrototype!"
        elif self.model is None:
            return str(self.name)
        else:
            return self.name + ' ' + str(self.model)


# ______________________________Organisation___________________________________
class Employee(models.Model):

    full_name:models.CharField = models.CharField(max_length=200)
    ...

    def __str__(self) -> str:
        if self is not None:
            return str(self.full_name)
        else:
            return 'empty employee'


class Storage(models.Model):

    location:models.CharField = models.CharField(max_length=200)
    ...

    def __str__(self) -> str:
        return self.location

# ______________________________Transactions___________________________________
class Inventory(models.Model):
    product_prototype:models.ForeignKey = models.ForeignKey(ProductPrototype, on_delete=models.PROTECT)
    storage:models.ForeignKey = models.ForeignKey(Storage, on_delete=models.PROTECT)
    on_employee:models.ForeignKey = models.ForeignKey(Employee, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    # NOTE in relese it'll be timestamp or FK to document.
    write_off:models.BooleanField = models.BooleanField(blank=True, default=False)


    def __str__(self) -> str:

        avaliable = ''
        if self.is_avaliable():
            avaliable = ' avaliable'

        if self.product_prototype is None:
            return "No prototype error!"
        elif self.storage is None:
            return "No storage error!"
        else:
            return str(self.product_prototype) + ' on ' + str(self.storage) + avaliable


    def is_avaliable(self):
        if self.write_off is False and self.on_employee is None:
            return True

inventory/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Count, QuerySet

from typing import Any, Dict

from .utils import  ViewModelContextMixin

from .models import Inventory, ProductPrototype

def index(request):
    return render(request, 'bases/base.html',
                  context={'title': 'Home', 'content':'<p>Some content</p>'})



class InventoryView(ViewModelContextMixin, ListView):
    # FIXME duplicate field in items
    #   field_titles must be a dict.
    #   on iter fields_titles from dict call it from items or ect.
    # TODO pagination
    # NOTE May be reserve another key for view with add 1:1 key to origin context items.

    model = Inventory
    template_name = 'inventory_list.html'
    context_object_name = 'items'



    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['title'] = 'Inventory'
        
        context['field_titles'] = [
            'Inventory_ID',
            'Product_name',
            'Storage_location',
            'User',
            'Write_off'
        ]
        context['items'] = [
            {
                'Inventory_ID': item.id,
                'Product_name': item.product_prototype,
                'Storage_location': item.storage,
                'User': item.on_employee if item.on_employee is not None else "",
                'Write_off': item.write_off if item.write_off == True else "" 
            }
            for item in context['items'].order_by('storage')
        ]
        
        return context
        

class ProductsAvaliableView(ListView):
    model = Inventory
    template_name = 'inventory_list.html'
    context_object_name = 'items'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Products avaliable'
        context['items'] = [
            {
                'product_id': item['product_prototype__pk'],
                'Product':"{product_name} {product_model}".format(
                    product_name = item['product_prototype__name'],
                    product_model= (
                        ''
                        if item['product_prototype__model__name'] is None
                        else item['product_prototype__model__name']
                    )
                ),
                'Count':item['count']
            }
            for item in context['items']
        ]

        context['field_titles'] = ['Product', 'Count']
        return context


    def get_queryset(self):
        qs = self.model.objects.filter(
            on_employee=None,
            write_off=False
        ).values(
            'product_prototype__pk',
            'product_prototype__name',
            'product_prototype__model__name'
            ).annotate(
            count = Count('id')
            )
        return qs
    

class StorageContainsView(InventoryView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'On Storages'
        return context


    def get_queryset(self):
        qs = super().get_queryset().filter(
            on_employee=None,
            write_off=False
        )
        return qs
        


class ShowInventory(ViewModelContextMixin, DetailView):
    # TODO 404
    model = Inventory
    template_name = "inventory_detail.html"
    pk_url_kwarg = 'id'
    
    context_object_name = "item"


    def get_context_data(self, **kwargs):
        su_context = super().get_context_data(**kwargs)
        mix_context = self.get_user_context()
        context = dict(list(su_context.items()) + list(mix_context.items()))
        return context
        

inventory/templates/bases/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{title}}{% endblock title %}</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gayathri:wght@100&display=swap" rel="stylesheet">
    <link type = "text/css" rel = "stylesheet" href = "{% static 'css/main.css' %}">
</head>
<body>
    {% include "bases/menu.html" %}
    <header><h1>{% block header %}{{title}}{% endblock header %}</h1></header>
    <content>{% block content%}<p>Some text</p>{% endblock content %}</content>
</body>
</html>

inventory/templates/bases/menu.html
<menu>
    <a href='/' class='material-symbols-outlined md32' title='Home'><p>home</p></a>
    <a href='/inventory' class='material-symbols-outlined md32' title='Inventory'><p>quick_reference_all</p></a>
</menu>

inventory/templates/inventory/group_view.html
{% regroup items by Storage_location as storage_list %}
{% for storage in storage_list %}
    <table class= 'table_view'>
        <thead>
            <tr>
                <th colspan="2">{{storage.grouper}}</th>
            </tr>
            <tr>
                <th>Product name</th>
                <th>Count</th>
            </tr>
        </thead>
        {% regroup storage.list|dictsort:"Product_name.id" by Product_name as product_list %}
            {% for item in product_list%}
                <tr>
                    <td>{{item.grouper}}</td>
                    <td>{{item.list|length}}</td>
                </tr> 
            {% endfor %}
    </table>
{% endfor %}

inventory/templates/inventory/table_view.html
<table class='table_view'>
    <thead>
    {% for field_title in field_titles%}
    <th>{{field_title}}</th>
    {% endfor %}
    </thead>

    <tbody>
    {% for item in items%}
        <tr {% if title == 'Inventory' %} onclick="location.href='/inventory/{{item.Inventory_ID}}'" type='button' {% endif %}>
            {% for key, value in item.items%}
                {% if key in field_titles%}<td>{{value}}</td>{% endif %}
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>    
</table>

inventory/templates/inventory_detail.html
{% extends 'bases/base.html' %}
{% block title%}{{title}}{% endblock title%}
{% block header%}{{title}}{% endblock header%}
{% block content  %}
    <table class='table_view truncated'>
        <tr>
            <th>Inventory ID</th><td>{{item.id}}</td>
        </tr>
        <tr>
            <th>Product name</th><td>{{item.product_prototype}}</td>
        </tr>
        <tr>
            <th>Storage location</th><td>{{item.storage}}</td>
        </tr>
        <tr>
            <th>User</th><td>{{item.on_employee}}</td>
        </tr>
        <tr>
            <th>Write off</th><td>{{item.write_off}}</td>
        </tr>
    </table>
{% endblock content  %}

inventory/templates/inventory_list.html
{% extends 'bases/base.html' %}

{% block title%}{{title}}{% endblock title%}
{% block header%}{{title}}{% endblock header%}
{% block content  %}
    <div class='controls'>
        <button onclick="location.href='/inventory/products/';">Products avaliable</button>
        <button onclick="location.href='/inventory/storages/';">Avaliable by storages</button>
    </div>
    {% if 'Products' in title or 'Inventory' in title %}
        {% include "inventory/table_view.html" with field_titles=field_titles items=items %}
    {% else %}
        {% include "inventory/group_view.html" with field_title=field_titles items=items %}
    {% endif %}

{% endblock content  %}